# Generated by Django 4.1.7 on 2023-08-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateory',
            new_name='category',
        ),
    ]
